<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="atrindade-note" failures="2" tests="8" name="Regression" time="0.048" errors="0" timestamp="23 jul 2020 13:29:44 GMT">
  <testcase classname="com.trindatech.MessageTest" name="testFour" time="0.009">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.trindatech.MessageTest" name="testFour" time="0.001">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.trindatech.MessageTest" name="testFour" time="0.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.trindatech.MessageTest.testFour(MessageTest.java:30)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testFour -->
  <testcase classname="com.trindatech.MessageTest" name="testOne" time="0.001">
    <skipped/>
  </testcase> <!-- testOne -->
  <testcase classname="com.trindatech.MessageTest" name="testOne" time="0.001">
    <skipped/>
  </testcase> <!-- testOne -->
  <testcase classname="com.trindatech.MessageTest" name="testOne" time="0.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.trindatech.MessageTest.testOne(MessageTest.java:12)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- testOne -->
  <testcase classname="com.trindatech.MessageTest" name="testThree" time="0.001"/>
  <testcase classname="com.trindatech.MessageTest" name="testTwo" time="0.002"/>
</testsuite> <!-- Regression -->
